service: yyt-binary-distribution-api
provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:GetObjectAcl'
        - 's3:PutObject'
        - 's3:PutObjectAcl'
        - 's3:DeleteObject'
      Resource:
        - 'arn:aws:s3:::${env:DIST_BUCKET}/*'
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::${env:DIST_BUCKET}'
    - Effect: 'Allow'
      Action:
        - 'cloudfront:CreateInvalidation'
      Resource:
        - Fn::Join:
            - ':'
            - - arn:aws:cloudfront
              - '' # No region for CloudFront
              - Ref: AWS::AccountId
              - distribution/${env:DIST_CF_ID}
    - Effect: 'Allow'
      Action:
        - 's3:HeadObject'
        - 's3:GetObject'
      Resource:
        - 'arn:aws:s3:::${env:CONFIG_BUCKET}/*'
  environment:
    CONFIG_BUCKET: ${env:CONFIG_BUCKET}
    DIST_CONFIG_TOKENS: ${env:DIST_CONFIG_TOKENS}
    DIST_BUCKET: ${env:DIST_BUCKET}
    DIST_DOMAIN: ${env:DIST_DOMAIN}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  createDistribution:
    handler: src/index.createDistribution
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: /{serviceName}/{platform}/{version}
          method: put
          request:
            parameters:
              paths:
                serviceName: true
                platform: true
                version: true
          cors: true
  deleteDistribution:
    handler: src/index.deleteDistribution
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: /{serviceName}/{platform}/{version}
          method: delete
          request:
            parameters:
              paths:
                serviceName: true
                platform: true
                version: true
          cors: true
  listAllDistributions:
    handler: src/index.listAllDistributions
    memorySize: 128
    timeout: 12
    events:
      - http:
          path: /{serviceName}
          method: get
          request:
            parameters:
              paths:
                serviceName: true
          cors: true
  listPlatformDistributions:
    handler: src/index.listPlatformDistributions
    memorySize: 128
    timeout: 12
    events:
      - http:
          path: /{serviceName}/{platform}
          method: get
          request:
            parameters:
              paths:
                serviceName: true
                platform: true
          cors: true
  getPlistForLatestIos:
    handler: src/index.getPlistForLatestIos
    memorySize: 128
    timeout: 12
    events:
      - http:
          path: /ios/{packageName}/{semver}/manifest.plist
          method: get
          request:
            parameters:
              paths:
                packageName: true
                semver: true
          cors: true

resources:
  Resources:
    DistBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:DIST_BUCKET}
        LifecycleConfiguration:
          Rules:
            - Id: Only90Days
              Status: Enabled
              ExpirationInDays: 90
              NoncurrentVersionExpirationInDays: 7
              AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 90
