service: yyt-binary-distribution-api
provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  region: ap-northeast-2
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:GetObjectAcl'
        - 's3:PutObject'
        - 's3:PutObjectAcl'
        - 's3:DeleteObject'
      Resource:
        - 'arn:aws:s3:::${env:DIST_BUCKET}/*'
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::${env:DIST_BUCKET}'
    - Effect: 'Allow'
      Action:
        - 'cloudfront:CreateInvalidation'
      Resource:
        - Fn::Join:
            - ':'
            - - arn:aws:cloudfront
              - '' # No region for CloudFront
              - Ref: AWS::AccountId
              - distribution/${env:DIST_CF_ID}
    - Effect: 'Allow'
      Action:
        - 's3:HeadObject'
        - 's3:GetObject'
      Resource:
        - 'arn:aws:s3:::${env:CONFIG_BUCKET}/*'
  environment:
    CONFIG_BUCKET: ${env:CONFIG_BUCKET}
    DIST_CONFIG_TOKENS: ${env:DIST_CONFIG_TOKENS}
    DIST_BUCKET: ${env:DIST_BUCKET}
    DIST_DOMAIN: ${env:DIST_DOMAIN}
    DIST_API_URL_PREFIX: ${env:DIST_API_URL_PREFIX}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

package:
  individually: true

custom:
  prune:
    automatic: true
    number: 7

functions:
  createDistribution:
    handler: src/put.createDistribution
    memorySize: 256
    timeout: 5
    events:
      - http:
          path: /{serviceName}/{platform}/{version}
          method: put
          cors: true
  deleteDistribution:
    handler: src/put.deleteDistribution
    memorySize: 256
    timeout: 5
    events:
      - http:
          path: /{serviceName}/{platform}/{version}
          method: delete
          cors: true
  listAllDistributions:
    handler: src/get.listAllDistributions
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: /{serviceName}
          method: get
          cors: true
  listPlatformDistributions:
    handler: src/get.listPlatformDistributions
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: /{serviceName}/{platform}
          method: get
          cors: true
  getPlistForLatestIos:
    handler: src/get.getPlistForLatestIos
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: /ios/{packageName}/{semver}/manifest.plist
          method: get
          cors: true
  redirectToIosManifest:
    handler: src/get.redirectToIosManifest
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: /ios-manifest/{packageName}/{semver}
          method: get
          cors: true
  findExpiredDistributions:
    handler: src/batch.findExpiredDistributions
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: /expiration
          method: get
          cors: true
  deleteExpiredDists:
    handler: src/batch.deleteExpiredDistributions
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: /expiration
          method: delete
      - schedule: cron(0 20 * * ? *)

resources:
  Resources:
    DistBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:DIST_BUCKET}
